### ISSUE TITLE
Support removing all unused revisions

### ISSUE THREAD

**Issue by niemeyer** [snapcore/snapd#2484]
Something like this:
```
$ snap remove --unused <snap>
```
That would remove old revisions that are currently unused by the given snap.

As an implementation note, "unused" means _not current_ internally. If the snap is disabled, all revisions will be currently disabled, but the current one should remain in the system if `--unused` is provided.

**Comment by niemeyer** [comment]
Some background here: https://bugs.launchpad.net/snapd/+bug/1555217

**Comment by zyga** [comment]
This issue has been moved to launchpad: https://bugs.launchpad.net/snapd/+bug/1657107
