### ISSUE TITLE
error: daemon is missing the listener for /run/snapd.socket

### ISSUE THREAD

**Issue by kozec** [snapcore/snapd#2537]
Hello.

In my so far vain attempt to get snapd running on non-ubuntu based distro (i.e. Manjaro), I can't get over this error message:

```
error: daemon is missing the listener for /run/snapd.socket
```

`/usr/lib/snapd/snapd` doesn't seems to take any parameters nor displays any help when called with -h/--help and even after going through source, I cannot figure where are values for [listenerMap](https://github.com/snapcore/snapd/blob/master/daemon/daemon.go#L186) supposed to come from.

So, I'm here to ask: How should I give daemon his listener?

**Comment by zyga** [comment]
The systemd socket unit for snapd (`snapd.socket`) defines this. If Manjaro is using systemd you can simply reuse the systemd unit directly.

BTW: I'd love to work with you, can you ping me on https://rocket.ubuntu.com/channel/snappy or on IRC (rocket is preferred as it works across disconnects better).

**Comment by kozec** [comment]
Ah, okay... And in that hypothetical case if I were using Manjaro with _openrc_ and had no systemd unit around?

Because that was big part of me trying to get snapd running :)

**Comment by zyga** [comment]
If you were to use openrc you'd have much bigger task ahead. The systemd unit is how snapd gets started, it expects to get socket file descriptors. Quickly googling for this I found a post by Lennart http://0pointer.de/blog/projects/socket-activation.html

While you can get snapd to start with openrc you won't be able to use it pretty much for anything as it requires systemd tools and semantics today.
