### ISSUE TITLE
snapd is not tested against Debian

### ISSUE THREAD

**Issue by zyga** [snapcore/snapd#2553]
Spread supports Debian but our test suite is not actively exercised against it. A quick rough look at this suggests that the following steps must be taken:

- [ ] Define a Debian (amd64) system in linode in spread.yaml
- [ ] Add Debian-specific prepare code for packaging, etc
- [ ] Separate any Ubuntu specific code from the generic Debian code
- [ ] Blacklist tests that rely on confinement
- [ ] Blacklist tests that rely on Ubuntu-specific features (if any)

Ideally it would be good to add an Debian (unstable) image to https://github.com/zyga/spread-qemu-images so that development can be done against locally-running qemu target.

**Comment by jamiedbennett** [comment]
+1, would be great to see this an other distros tested with spread.

**Comment by zyga** [comment]
This issue has been moved to launchpad: https://bugs.launchpad.net/snapd/+bug/1657101
