### ISSUE TITLE
seccomp tests fail on Ubuntu 16.04 in when running in qemu or linode

### ISSUE THREAD

**Issue by zyga** [snapcore/snapd#2559]
Not sure why this only affects qemu and linode yet.

I've been investigating failures related to https://github.com/snapcore/snapd/pull/2433

With some extra analysis I focused on one specific failure ``test_bad_seccomp_filter_args_null`.

I've added some debugging around seccomp code and ended up with a trace that shows we fail to load the constructed seccomp profile into the kernel, as can be shown by this trace:

```
DEBUG: loading seccomp profile into the kernel
Bad system call
```

The profile is probably malformed so I added tracing to see what we construct and ended up with this:

```
DEBUG: adding the following seccomp rules
DEBUG: Input line: open
DEBUG: seccomp rule: ALLOW sycall 2
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: close
DEBUG: seccomp rule: ALLOW sycall 3
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: mmap
DEBUG: seccomp rule: ALLOW sycall 9
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: mmap2
DEBUG: seccomp rule: ALLOW sycall -10029
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: munmap
DEBUG: seccomp rule: ALLOW sycall 11
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: mprotect
DEBUG: seccomp rule: ALLOW sycall 10
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: fstat
DEBUG: seccomp rule: ALLOW sycall 5
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: fstat64
DEBUG: seccomp rule: ALLOW sycall -10010
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: access
DEBUG: seccomp rule: ALLOW sycall 21
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: read
DEBUG: seccomp rule: ALLOW sycall 0
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: brk
DEBUG: seccomp rule: ALLOW sycall 12
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: execve
DEBUG: seccomp rule: ALLOW sycall 59
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: arch_prctl
DEBUG: seccomp rule: ALLOW sycall 158
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: exit_group
DEBUG: seccomp rule: ALLOW sycall 231
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: geteuid
DEBUG: seccomp rule: ALLOW sycall 107
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: geteuid32
DEBUG: seccomp rule: ALLOW sycall -10016
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: getuid
DEBUG: seccomp rule: ALLOW sycall 102
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: set_thread_area
DEBUG: seccomp rule: ALLOW sycall 205
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
DEBUG: Input line: socket SOCK_STREAM
DEBUG: seccomp rule: ALLOW sycall 41
DEBUG:   0: arg:0 op; 4 (SCMP_CMP_EQ), datum_a: 0x1, datum_b: 0
DEBUG: NOTE: seccomp_rule_add_exact_array failed, trying seccomp_rule_add_array instead
```

NOTE: the failure comes from the following part of the test

```shell
# an embedded null that is after a valid arg stops processing of the arg
# (limitation of fgets() implementation)
printf "Test ok seccomp arg filtering (socket SOCK_STREAM\\\0bad stuff)"
cat "$TMP"/tmpl >"$TMP"/snap.name.app
printf "socket SOCK_STREAM\0bad stuff\n" >>"$TMP"/snap.name.app

if SNAP_CONFINE_DEBUG=yes $L snap.name.app /bin/true 2>/tmp/debug.log; then
    PASS
else
    cat "$TMP"/snap.name.app
    FAIL
fi
```

The version of seccomp on my host where this works is exactly the same as in the qemu vm `2.2.3-3ubuntu3`

**Comment by zyga** [comment]
All of the above was tested on amd64.

Those negative syscalls puzzled me so I had a look at what should `mmap2` be on `amd64` and...
```
zyga@xenial-server:/home/zyga2/go/src/github.com/snapcore/snapd$ grep -R __NR_mmap2 /usr/include/

/usr/include/x86_64-linux-gnu/asm/unistd_32.h:#define __NR_mmap2 192
/usr/include/x86_64-linux-gnu/bits/syscall.h:#define SYS_mmap2 __NR_mmap2
```

**Comment by zyga** [comment]
Tail of the strace of this  failure is also interesting but just confirms that what really fails is profile insertion:

```
write(2, "DEBUG: ", 7)                  = 7
write(2, "loading seccomp profile into the"..., 39) = 39
write(2, "\n", 1)                       = 1
prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, {len = 50, filter = 0x746370}) = 0
+++ killed by SIGSYS +++
```

**Comment by zyga** [comment]
Looking at seccomp (the userspace library) I then see this:
```
#define __PNR_mmap2     -10029
```

Any idea why those would be different from kernel declarations?

**Comment by zyga** [comment]
(how great it is that syscalls have different values everywhere)

```
zyga@xenial-server:~/seccomp-debug/libseccomp-2.2.3/src$ grep -R mmap2 .
./arch-mips-syscalls.c:	{ "mmap2", (__NR_SYSCALL_BASE + 210) },
./arch-s390-syscalls.c:	{ "mmap2", 192 },
./arch-mips64-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-s390x-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-ppc64-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-x86_64-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-arm-syscalls.c:	{ "mmap2", (__NR_SYSCALL_BASE + 192) },
./arch-x32-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-mips64n32-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-x86-syscalls.c:	{ "mmap2", 192 },
./arch-aarch64-syscalls.c:	{ "mmap2", __PNR_mmap2 },
./arch-ppc-syscalls.c:	{ "mmap2", 192 },
```

**Comment by zyga** [comment]
So at least it seems that seccomp is correctly resolving `mmap2` to `-10029` when on `amd64`

**Comment by zyga** [comment]
All of this was tested on the up-to-date xenial kernel: `Linux autopkgtest 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jdstrand** [comment]
From irc:
"
07:38 < jdstrand> zyga: https://github.com/snapcore/snapd/issue/2559 gives a 404. 
                  based on what you pasted, it is saying that mmap2 is allowed by the 
                  snappy policy but is unknown on the system that snapd is running 
                  on. based on 
                  http://people.canonical.com/~ubuntu-security/syscalls/, mmap2 was 
                  introduced in kernel 3.19
07:40 < jdstrand> zyga: perhaps the application is a statically compiled application 
                  that uses mmap2? perhaps the application is using a library that 
                  uses mmap2
07:41 < zyga> jdstrand: we run /bin/true
07:41 < zyga> jdstrand: that's the old test
07:41 < jdstrand> zyga: nothing in your paste indicates the profile is malformed
"

The 'paste' I am referring to above is 
https://github.com/snapcore/snapd/issues/2559#issue-198950475.

The thing to keep in mind is that the way that we setup our filter, we have a list of syscalls for all architectures and kernels. eg, mmap2 is listed even though it was only introduced in kernel 3.19. set_tls is listed even though it only exists on arm. The debug output is misleading because it will allow unknown syscalls (they show up as negative numbers) and we also first try to do an exact match (seccomp_rule_add_exact_array) but if that fails due to something with the architecture, we then use use seccomp_rule_add_array. Also, PNR are 'pseudo syscalls' and are simply an internal mechanism seccomp uses to handle unknown syscalls for this arch/ABI.

Instead of focusing on that debug output you pasted, focus on the denied syscall. Since you have 'Bad system call' in your output, what is the logged seccomp denial in kern.log at the time this happens?

**Comment by zyga** [comment]
@jdstrand interesting idea. The kernel logs the following thing:
```
Jan  5 15:00:10 autopkgtest kernel: [ 9789.846507] audit: type=1326 audit(1483624810.841:327): auid=1000 uid=0 gid=0 ses=1 pid=22116 comm="snap-confine" exe="/home/gopath/src/github.com/snapcore/snapd/cmd/autogarbage/snap-confine/snap-confine" sig=31 arch=c000003e syscall=1 compat=0 ip=0x7f41b5c126e0 code=0x0
```

**Comment by jdstrand** [comment]
'1' is 'write' on amd64. 'write' is not included in common.sh. Interesting that /bin/true needs 'write'-- is it failing for some other reason and trying to log error output?

**Comment by zyga** [comment]
It seems this was it! As the code evolved it seems that snap-confine may need extra syscalls to just finish working and run the other program.

**Comment by zyga** [comment]
This was traced to a list of extra syscalls, closing.
